relativeURLs = true
title = "Byungki Mun"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Candidate, Virginia Tech"
    logo = "Byungki Mun.jpg" 
    
